// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8J4lOng0IDT47cMPx2rMqbOTQ82wjX1Y',
    appId: '1:142807384290:web:c3590b0805bb21d7bc1ebb',
    messagingSenderId: '142807384290',
    projectId: 'fasum-stephen',
    authDomain: 'fasum-stephen.firebaseapp.com',
    storageBucket: 'fasum-stephen.firebasestorage.app',
    measurementId: 'G-ECJQE6WJ6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9e9BbIAtK-nlkn-cwryjFsMl9zbnt0_w',
    appId: '1:142807384290:android:bb4b76f45f656448bc1ebb',
    messagingSenderId: '142807384290',
    projectId: 'fasum-stephen',
    storageBucket: 'fasum-stephen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQIlkPBsGKKtJUhqLXHSGIlV9TzZk5Qs',
    appId: '1:142807384290:ios:ef54b005f8099fa6bc1ebb',
    messagingSenderId: '142807384290',
    projectId: 'fasum-stephen',
    storageBucket: 'fasum-stephen.firebasestorage.app',
    iosBundleId: 'com.example.fasumStephen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQIlkPBsGKKtJUhqLXHSGIlV9TzZk5Qs',
    appId: '1:142807384290:ios:ef54b005f8099fa6bc1ebb',
    messagingSenderId: '142807384290',
    projectId: 'fasum-stephen',
    storageBucket: 'fasum-stephen.firebasestorage.app',
    iosBundleId: 'com.example.fasumStephen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8J4lOng0IDT47cMPx2rMqbOTQ82wjX1Y',
    appId: '1:142807384290:web:d7e2196d81c7408fbc1ebb',
    messagingSenderId: '142807384290',
    projectId: 'fasum-stephen',
    authDomain: 'fasum-stephen.firebaseapp.com',
    storageBucket: 'fasum-stephen.firebasestorage.app',
    measurementId: 'G-E2NTWBCHEL',
  );
}
